language: go

go:
  - 1.16.x

git:
  depth: false
  quiet: true
  submodules: false

branches:
  only:
    - master

script:
  - make build

before_deploy:
  - git config --local user.name "jreisinger"
  - git config --local user.email "jozef.reisinger@gmail.com"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "cmd/checkip-linux-amd64"
    - "cmd/checkip-darwin-amd64"
  skip_cleanup: true
